"""email_accounts connection lifecycle

Revision ID: 4f5bd3329298
Revises: 419df1184d05
Create Date: 2026-09-17 20:51:44.320187

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5bd3329298'
down_revision: str | None = '419df1184d05'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_accounts', sa.Column('external_account_id', sa.String(length=255), nullable=True))
    op.add_column('email_accounts', sa.Column('encrypted_refresh_token', sa.Text(), nullable=True))
    op.add_column('email_accounts', sa.Column('last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('email_accounts', sa.Column('connected_at', sa.DateTime(), nullable=True))
    op.add_column('email_accounts', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('email_accounts', sa.Column('last_error', sa.String(length=512), nullable=True))
    op.drop_index('uq_email_accounts_provider', table_name='email_accounts')
    op.create_unique_constraint(op.f('uq_email_accounts_user_id'), 'email_accounts', ['user_id', 'provider', 'external_account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_email_accounts_user_id'), 'email_accounts', type_='unique')
    op.create_index('uq_email_accounts_provider', 'email_accounts', ['provider', 'email_address'], unique=True)
    op.drop_column('email_accounts', 'last_error')
    op.drop_column('email_accounts', 'token_expires_at')
    op.drop_column('email_accounts', 'connected_at')
    op.drop_column('email_accounts', 'last_sync_at')
    op.drop_column('email_accounts', 'encrypted_refresh_token')
    op.drop_column('email_accounts', 'external_account_id')
    # ### end Alembic commands ###
